version: "3.5"

services:

  jaeger-agent:
    hostname: 'jaeger-agent'
    container_name: 'jaeger-agent'
    image: jaegertracing/jaeger-agent
    command: [ "--reporter.grpc.host-port=otel-col:14260"]
    ports:
      - 5775:5775/udp
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
    links:
      - otelcol
    depends_on:
      - otelcol

  jaeger:
    hostname: 'jaeger'
    container_name: 'jaeger'
    image: jaegertracing/all-in-one
    ports:
      - 16686:16686
      - 14268:14268
      - 14250:14250
      - 9411:9411
      - 4317
    environment:
      - 'COLLECTOR_OTLP_ENABLED=true'

  address-api:
    build:
      context: '.'
      dockerfile: 'Dockerfile-Address-Api'
    hostname: 'address-api'
    container_name: 'address-api'
    ports:
      - 8081:8081
    links:
      - jaeger-agent
      - application-db
    environment:
      - 'JAEGER_SAMPLER_TYPE=probabilistic'
      - 'JAEGER_SAMPLER_PARAM=1'
      - 'JAEGER_SAMPLER_MANAGER_HOST_PORT=jeager:5778'
      - 'JAEGER_REPORTER_LOG_SPANS=true'
      - 'JAEGER_AGENT_HOST=jaeger-agent'
      - 'JAEGER_AGENT_PORT=6831'
      - 'JAEGER_REPORTER_FLUSH_INTERVAL=1000'
      - 'JAEGER_REPORTER_MAX_QUEUE_SIZE=100'
      - 'JAEGER_SERVICE_NAME=address-api'
      - 'DATABASE_HOST=application-db'

  person-api:
    build:
      context: '.'
      dockerfile: 'Dockerfile-Person-Api'
    hostname: 'person-api'
    container_name: 'person-api'
    ports:
      - 8080:8080
    links:
      - jaeger-agent
      - application-db
    environment:
      - 'ADDRESS_API_HOST=address-api'
      - 'JAEGER_SAMPLER_TYPE=probabilistic'
      - 'JAEGER_SAMPLER_PARAM=1'
      - 'JAEGER_SAMPLER_MANAGER_HOST_PORT=jeager:5778'
      - 'JAEGER_REPORTER_LOG_SPANS=true'
      - 'JAEGER_AGENT_HOST=jaeger-agent'
      - 'JAEGER_AGENT_PORT=6831'
      - 'JAEGER_REPORTER_FLUSH_INTERVAL=1000'
      - 'JAEGER_REPORTER_MAX_QUEUE_SIZE=100'
      - 'JAEGER_SERVICE_NAME=person-api'
      - 'DATABASE_HOST=application-db'

  application-db:
    image: postgres:13.11
    container_name: application-db
    hostname: application-db
    volumes:
      - ./address-api/src/main/resources/01-address-table.sql:/docker-entrypoint-initdb.d/01-address-table.sql
      - ./address-api/src/main/resources/02-address-data.sql:/docker-entrypoint-initdb.d/02-address-data.sql
      - ./person-api/src/main/resources/01-person-table.sql:/docker-entrypoint-initdb.d/01-person-table.sql
    environment:
      POSTGRES_PASSWORD: "admin123"
    ports:
      - "5432:5432"

  otelcol:
    image: otel/opentelemetry-collector-contrib:0.76.1
    container_name: otel-col
    hostname: otel-col
    deploy:
      resources:
        limits:
          memory: 125M
    restart: unless-stopped
    command: [ "--config=/etc/opentelemetry-collector-jaeger.yaml" ]
    volumes:
      - ./opentelemetry-config/opentelemetry-collector-jaeger.yaml:/etc/opentelemetry-collector-jaeger.yaml
    ports:
      - "4317"          # OTLP over gRPC receiver
      - "4318:4318"     # OTLP over HTTP receiver
      - "14260:14260"   # jeager receiver
      - "8888"          # metrics endpoint
    links:
      - jaeger
    depends_on:
      - jaeger
